name: Build Project node
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  Build:
    strategy:
        fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install modules
      run: npm install

    - name: Build node.js
      run: npm run build