name: Test Project node
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
jobs:
  Tests:
    strategy:
        fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install modules
      run: npm install

    - name: Check prettier
      run: npm run prettier:ci

    - name: Check format
      if: ${{ always() }}
      run: npm run lint
      
    - name: Test node
      if: ${{ always() }}
      run: npm test